# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Team.destroy_all
Game.destroy_all
Week.destroy_all
User.destroy_all

team_names = %w[
Bears
Packers
Lions
Vikings

Falcons
Panthers
Saints
Buccaneers

Cowboys
Giants
Eagles
Redskins

Cardinals
49ers
Seahawks
Rams

Ravens
Bengals
Browns
Steelers

Texans
Colts
Jaguars
Titans

Bills
Dolphins
Patriots
Jets

Broncos
Chiefs
Raiders
Chargers
]

team_names.each do |name|
  Team.create(name: name)
end

a_aj     = User.create(name: 'A & AJ')
alx_lh   = User.create(name: 'Alx/Lh')
ann      = User.create(name: 'Ann')
anthony  = User.create(name: 'Anthony')
barb     = User.create(name: 'Barb')
ben_t    = User.create(name: 'Ben T')
bruce    = User.create(name: 'Bruce')
charles  = User.create(name: 'Charles')
danny    = User.create(name: 'Danny')
don      = User.create(name: 'Don')
jacob    = User.create(name: 'Jacob')
kim_jon  = User.create(name: 'Kim/Jon')
kristina = User.create(name: 'Kristina')
mary_z   = User.create(name: 'Mary Z')
matt     = User.create(name: 'Matt')
michael  = User.create(name: 'Michael')
paul     = User.create(name: 'Paul')
sarah    = User.create(name: 'Sarah')
tommy    = User.create(name: 'Tommy')
vince    = User.create(name: 'Vince')
zak_fam  = User.create(name: 'Zak Fam')

week13 = Week.create(year: 2014, week_number: 13)

bears_at_lions       = Game.between('Bears', 'Lions',        Time.new(2014,11,27,11,30,0,"+06:00"))
eagles_at_cowboys    = Game.between('Eagles', 'Cowboys',     Time.new(2014,11,27,15,30,0,"+06:00"))
seahawks_at_49ers    = Game.between('Seahawks', '49ers',     Time.new(2014,11,27,19,30,0,"+06:00"))
browns_at_bills      = Game.between('Browns', 'Bills',       Time.new(2014,11,30,12,00,0,"+06:00"))
chargers_at_ravens   = Game.between('Chargers', 'Ravens',    Time.new(2014,11,30,12,00,0,"+06:00"))
panthers_at_vikings  = Game.between('Panthers', 'Vikings',   Time.new(2014,11,30,12,00,0,"+06:00"))
bengals_at_bucs      = Game.between('Bengals', 'Buccaneers', Time.new(2014,11,30,12,00,0,"+06:00"))
titans_at_texans     = Game.between('Titans', 'Texans',      Time.new(2014,11,30,12,00,0,"+06:00"))
redskins_at_colts    = Game.between('Redskins', 'Colts',     Time.new(2014,11,30,12,00,0,"+06:00"))
giants_at_jaguars    = Game.between('Giants', 'Jaguars',     Time.new(2014,11,30,12,00,0,"+06:00"))
saints_at_steelers   = Game.between('Saints', 'Steelers',    Time.new(2014,11,30,12,00,0,"+06:00"))
raiders_at_rams      = Game.between('Raiders', 'Rams',       Time.new(2014,11,30,12,00,0,"+06:00"))
cardinals_at_falcons = Game.between('Cardinals', 'Falcons',  Time.new(2014,11,30,15,05,0,"+06:00"))
patriots_at_packers  = Game.between('Patriots', 'Packers',   Time.new(2014,11,30,15,25,0,"+06:00"))
broncos_at_chiefs    = Game.between('Broncos', 'Chiefs',     Time.new(2014,11,30,19,30,0,"+06:00"))
dolphins_at_jets     = Game.between('Dolphins', 'Jets',      Time.new(2014,12,01,19,30,0,"+06:00"))

week13.games << bears_at_lions
week13.games << eagles_at_cowboys
week13.games << seahawks_at_49ers
week13.games << browns_at_bills
week13.games << chargers_at_ravens
week13.games << panthers_at_vikings
week13.games << bengals_at_bucs
week13.games << titans_at_texans
week13.games << redskins_at_colts
week13.games << giants_at_jaguars
week13.games << saints_at_steelers
week13.games << raiders_at_rams
week13.games << cardinals_at_falcons
week13.games << patriots_at_packers
week13.games << broncos_at_chiefs
week13.games << dolphins_at_jets

Pick.create(game_id: bears_at_lions.id, user_id: bruce.id,    is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: matt.id,     is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: kristina.id, is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: danny.id,    is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: don.id,      is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: zak_fam.id,  is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: paul.id,     is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: sarah.id,    is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: charles.id,  is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: barb.id,     is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: vince.id,    is_home_team: false)
Pick.create(game_id: bears_at_lions.id, user_id: anthony.id,  is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: kim_jon.id,  is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: mary_z.id,   is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: alx_lh.id,   is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: ben_t.id,    is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: michael.id,  is_home_team: false)
Pick.create(game_id: bears_at_lions.id, user_id: a_aj.id,     is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: tommy.id,    is_home_team: true)
Pick.create(game_id: bears_at_lions.id, user_id: jacob.id,    is_home_team: false)
Pick.create(game_id: bears_at_lions.id, user_id: ann.id,      is_home_team: true)

Pick.create(game_id: eagles_at_cowboys.id, user_id: bruce.id,    is_home_team: true)
Pick.create(game_id: eagles_at_cowboys.id, user_id: matt.id,     is_home_team: true)
Pick.create(game_id: eagles_at_cowboys.id, user_id: kristina.id, is_home_team: true)
Pick.create(game_id: eagles_at_cowboys.id, user_id: danny.id,    is_home_team: true)
Pick.create(game_id: eagles_at_cowboys.id, user_id: don.id,      is_home_team: true)
Pick.create(game_id: eagles_at_cowboys.id, user_id: zak_fam.id,  is_home_team: false)
Pick.create(game_id: eagles_at_cowboys.id, user_id: paul.id,     is_home_team: false)
Pick.create(game_id: eagles_at_cowboys.id, user_id: sarah.id,    is_home_team: true)
Pick.create(game_id: eagles_at_cowboys.id, user_id: charles.id,  is_home_team: true)
Pick.create(game_id: eagles_at_cowboys.id, user_id: barb.id,     is_home_team: false)
Pick.create(game_id: eagles_at_cowboys.id, user_id: vince.id,    is_home_team: true)
Pick.create(game_id: eagles_at_cowboys.id, user_id: anthony.id,  is_home_team: false)
Pick.create(game_id: eagles_at_cowboys.id, user_id: kim_jon.id,  is_home_team: true)
Pick.create(game_id: eagles_at_cowboys.id, user_id: mary_z.id,   is_home_team: true)
Pick.create(game_id: eagles_at_cowboys.id, user_id: alx_lh.id,   is_home_team: true)
Pick.create(game_id: eagles_at_cowboys.id, user_id: ben_t.id,    is_home_team: false)
Pick.create(game_id: eagles_at_cowboys.id, user_id: michael.id,  is_home_team: false)
Pick.create(game_id: eagles_at_cowboys.id, user_id: a_aj.id,     is_home_team: true)
Pick.create(game_id: eagles_at_cowboys.id, user_id: tommy.id,    is_home_team: true)
Pick.create(game_id: eagles_at_cowboys.id, user_id: jacob.id,    is_home_team: false)
Pick.create(game_id: eagles_at_cowboys.id, user_id: ann.id,      is_home_team: true)

Pick.create(game_id: seahawks_at_49ers.id, user_id: bruce.id,    is_home_team: true)
Pick.create(game_id: seahawks_at_49ers.id, user_id: matt.id,     is_home_team: true)
Pick.create(game_id: seahawks_at_49ers.id, user_id: kristina.id, is_home_team: true)
Pick.create(game_id: seahawks_at_49ers.id, user_id: danny.id,    is_home_team: false)
Pick.create(game_id: seahawks_at_49ers.id, user_id: don.id,      is_home_team: false)
Pick.create(game_id: seahawks_at_49ers.id, user_id: zak_fam.id,  is_home_team: false)
Pick.create(game_id: seahawks_at_49ers.id, user_id: paul.id,     is_home_team: true)
Pick.create(game_id: seahawks_at_49ers.id, user_id: sarah.id,    is_home_team: false)
Pick.create(game_id: seahawks_at_49ers.id, user_id: charles.id,  is_home_team: false)
Pick.create(game_id: seahawks_at_49ers.id, user_id: barb.id,     is_home_team: false)
Pick.create(game_id: seahawks_at_49ers.id, user_id: vince.id,    is_home_team: true)
Pick.create(game_id: seahawks_at_49ers.id, user_id: anthony.id,  is_home_team: false)
Pick.create(game_id: seahawks_at_49ers.id, user_id: kim_jon.id,  is_home_team: false)
Pick.create(game_id: seahawks_at_49ers.id, user_id: mary_z.id,   is_home_team: true)
Pick.create(game_id: seahawks_at_49ers.id, user_id: alx_lh.id,   is_home_team: false)
Pick.create(game_id: seahawks_at_49ers.id, user_id: ben_t.id,    is_home_team: true)
Pick.create(game_id: seahawks_at_49ers.id, user_id: michael.id,  is_home_team: false)
Pick.create(game_id: seahawks_at_49ers.id, user_id: a_aj.id,     is_home_team: false)
Pick.create(game_id: seahawks_at_49ers.id, user_id: tommy.id,    is_home_team: false)
Pick.create(game_id: seahawks_at_49ers.id, user_id: jacob.id,    is_home_team: false)
Pick.create(game_id: seahawks_at_49ers.id, user_id: ann.id,      is_home_team: true)

Pick.create(game_id: redskins_at_colts.id, user_id: bruce.id,    is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: matt.id,     is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: kristina.id, is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: danny.id,    is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: don.id,      is_home_team: true)
# Pick.create(game_id: redskins_at_colts.id, user_id: zak_fam.id,  is_home_team: nil)
Pick.create(game_id: redskins_at_colts.id, user_id: paul.id,     is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: sarah.id,    is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: charles.id,  is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: barb.id,     is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: vince.id,    is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: anthony.id,  is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: kim_jon.id,  is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: mary_z.id,   is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: alx_lh.id,   is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: ben_t.id,    is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: michael.id,  is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: a_aj.id,     is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: tommy.id,    is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: jacob.id,    is_home_team: true)
Pick.create(game_id: redskins_at_colts.id, user_id: ann.id,      is_home_team: true)

Pick.create(game_id: titans_at_texans.id, user_id: bruce.id,    is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: matt.id,     is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: kristina.id, is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: danny.id,    is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: don.id,      is_home_team: true)
# Pick.create(game_id: titans_at_texans.id, user_id: zak_fam.id,  is_home_team: nil)
Pick.create(game_id: titans_at_texans.id, user_id: paul.id,     is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: sarah.id,    is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: charles.id,  is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: barb.id,     is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: vince.id,    is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: anthony.id,  is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: kim_jon.id,  is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: mary_z.id,   is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: alx_lh.id,   is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: ben_t.id,    is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: michael.id,  is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: a_aj.id,     is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: tommy.id,    is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: jacob.id,    is_home_team: true)
Pick.create(game_id: titans_at_texans.id, user_id: ann.id,      is_home_team: true)

Pick.create(game_id: browns_at_bills.id, user_id: bruce.id,    is_home_team: true)
Pick.create(game_id: browns_at_bills.id, user_id: matt.id,     is_home_team: true)
Pick.create(game_id: browns_at_bills.id, user_id: kristina.id, is_home_team: false)
Pick.create(game_id: browns_at_bills.id, user_id: danny.id,    is_home_team: true)
Pick.create(game_id: browns_at_bills.id, user_id: don.id,      is_home_team: true)
# Pick.create(game_id: browns_at_bills.id, user_id: zak_fam.id,  is_home_team: nil)
Pick.create(game_id: browns_at_bills.id, user_id: paul.id,     is_home_team: true)
Pick.create(game_id: browns_at_bills.id, user_id: sarah.id,    is_home_team: true)
Pick.create(game_id: browns_at_bills.id, user_id: charles.id,  is_home_team: true)
Pick.create(game_id: browns_at_bills.id, user_id: barb.id,     is_home_team: true)
Pick.create(game_id: browns_at_bills.id, user_id: vince.id,    is_home_team: true)
Pick.create(game_id: browns_at_bills.id, user_id: anthony.id,  is_home_team: false)
Pick.create(game_id: browns_at_bills.id, user_id: kim_jon.id,  is_home_team: false)
Pick.create(game_id: browns_at_bills.id, user_id: mary_z.id,   is_home_team: false)
Pick.create(game_id: browns_at_bills.id, user_id: alx_lh.id,   is_home_team: false)
Pick.create(game_id: browns_at_bills.id, user_id: ben_t.id,    is_home_team: false)
Pick.create(game_id: browns_at_bills.id, user_id: michael.id,  is_home_team: true)
Pick.create(game_id: browns_at_bills.id, user_id: a_aj.id,     is_home_team: true)
Pick.create(game_id: browns_at_bills.id, user_id: tommy.id,    is_home_team: false)
Pick.create(game_id: browns_at_bills.id, user_id: jacob.id,    is_home_team: false)
Pick.create(game_id: browns_at_bills.id, user_id: ann.id,      is_home_team: false)

Pick.create(game_id: chargers_at_ravens.id, user_id: bruce.id,    is_home_team: true)
Pick.create(game_id: chargers_at_ravens.id, user_id: matt.id,     is_home_team: true)
Pick.create(game_id: chargers_at_ravens.id, user_id: kristina.id, is_home_team: false)
Pick.create(game_id: chargers_at_ravens.id, user_id: danny.id,    is_home_team: true)
Pick.create(game_id: chargers_at_ravens.id, user_id: don.id,      is_home_team: true)
# Pick.create(game_id: chargers_at_ravens.id, user_id: zak_fam.id,  is_home_team: nil)
Pick.create(game_id: chargers_at_ravens.id, user_id: paul.id,     is_home_team: true)
Pick.create(game_id: chargers_at_ravens.id, user_id: sarah.id,    is_home_team: true)
Pick.create(game_id: chargers_at_ravens.id, user_id: charles.id,  is_home_team: true)
Pick.create(game_id: chargers_at_ravens.id, user_id: barb.id,     is_home_team: true)
Pick.create(game_id: chargers_at_ravens.id, user_id: vince.id,    is_home_team: true)
Pick.create(game_id: chargers_at_ravens.id, user_id: anthony.id,  is_home_team: true)
Pick.create(game_id: chargers_at_ravens.id, user_id: kim_jon.id,  is_home_team: true)
Pick.create(game_id: chargers_at_ravens.id, user_id: mary_z.id,   is_home_team: false)
Pick.create(game_id: chargers_at_ravens.id, user_id: alx_lh.id,   is_home_team: true)
Pick.create(game_id: chargers_at_ravens.id, user_id: ben_t.id,    is_home_team: true)
Pick.create(game_id: chargers_at_ravens.id, user_id: michael.id,  is_home_team: true)
Pick.create(game_id: chargers_at_ravens.id, user_id: a_aj.id,     is_home_team: true)
Pick.create(game_id: chargers_at_ravens.id, user_id: tommy.id,    is_home_team: true)
Pick.create(game_id: chargers_at_ravens.id, user_id: jacob.id,    is_home_team: false)
Pick.create(game_id: chargers_at_ravens.id, user_id: ann.id,      is_home_team: false)

Pick.create(game_id: giants_at_jaguars.id, user_id: bruce.id,    is_home_team: false)
Pick.create(game_id: giants_at_jaguars.id, user_id: matt.id,     is_home_team: false)
Pick.create(game_id: giants_at_jaguars.id, user_id: kristina.id, is_home_team: false)
Pick.create(game_id: giants_at_jaguars.id, user_id: danny.id,    is_home_team: false)
Pick.create(game_id: giants_at_jaguars.id, user_id: don.id,      is_home_team: false)
# Pick.create(game_id: giants_at_jaguars.id, user_id: zak_fam.id,  is_home_team: nil)
Pick.create(game_id: giants_at_jaguars.id, user_id: paul.id,     is_home_team: false)
Pick.create(game_id: giants_at_jaguars.id, user_id: sarah.id,    is_home_team: false)
Pick.create(game_id: giants_at_jaguars.id, user_id: charles.id,  is_home_team: false)
Pick.create(game_id: giants_at_jaguars.id, user_id: barb.id,     is_home_team: false)
Pick.create(game_id: giants_at_jaguars.id, user_id: vince.id,    is_home_team: false)
Pick.create(game_id: giants_at_jaguars.id, user_id: anthony.id,  is_home_team: true)
Pick.create(game_id: giants_at_jaguars.id, user_id: kim_jon.id,  is_home_team: false)
Pick.create(game_id: giants_at_jaguars.id, user_id: mary_z.id,   is_home_team: false)
Pick.create(game_id: giants_at_jaguars.id, user_id: alx_lh.id,   is_home_team: false)
Pick.create(game_id: giants_at_jaguars.id, user_id: ben_t.id,    is_home_team: false)
Pick.create(game_id: giants_at_jaguars.id, user_id: michael.id,  is_home_team: false)
Pick.create(game_id: giants_at_jaguars.id, user_id: a_aj.id,     is_home_team: false)
Pick.create(game_id: giants_at_jaguars.id, user_id: tommy.id,    is_home_team: true)
Pick.create(game_id: giants_at_jaguars.id, user_id: jacob.id,    is_home_team: false)
Pick.create(game_id: giants_at_jaguars.id, user_id: ann.id,      is_home_team: true)

Pick.create(game_id: bengals_at_bucs.id, user_id: bruce.id,    is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: matt.id,     is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: kristina.id, is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: danny.id,    is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: don.id,      is_home_team: false)
# Pick.create(game_id: bengals_at_bucs.id, user_id: zak_fam.id,  is_home_team: nil)
Pick.create(game_id: bengals_at_bucs.id, user_id: paul.id,     is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: sarah.id,    is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: charles.id,  is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: barb.id,     is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: vince.id,    is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: anthony.id,  is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: kim_jon.id,  is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: mary_z.id,   is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: alx_lh.id,   is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: ben_t.id,    is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: michael.id,  is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: a_aj.id,     is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: tommy.id,    is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: jacob.id,    is_home_team: false)
Pick.create(game_id: bengals_at_bucs.id, user_id: ann.id,      is_home_team: false)

Pick.create(game_id: raiders_at_rams.id, user_id: bruce.id,    is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: matt.id,     is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: kristina.id, is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: danny.id,    is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: don.id,      is_home_team: true)
# Pick.create(game_id: raiders_at_rams.id, user_id: zak_fam.id,  is_home_team: nil)
Pick.create(game_id: raiders_at_rams.id, user_id: paul.id,     is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: sarah.id,    is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: charles.id,  is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: barb.id,     is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: vince.id,    is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: anthony.id,  is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: kim_jon.id,  is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: mary_z.id,   is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: alx_lh.id,   is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: ben_t.id,    is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: michael.id,  is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: a_aj.id,     is_home_team: false)
Pick.create(game_id: raiders_at_rams.id, user_id: tommy.id,    is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: jacob.id,    is_home_team: true)
Pick.create(game_id: raiders_at_rams.id, user_id: ann.id,      is_home_team: false)

Pick.create(game_id: saints_at_steelers.id, user_id: bruce.id,    is_home_team: true)
Pick.create(game_id: saints_at_steelers.id, user_id: matt.id,     is_home_team: true)
Pick.create(game_id: saints_at_steelers.id, user_id: kristina.id, is_home_team: true)
Pick.create(game_id: saints_at_steelers.id, user_id: danny.id,    is_home_team: true)
Pick.create(game_id: saints_at_steelers.id, user_id: don.id,      is_home_team: false)
# Pick.create(game_id: saints_at_steelers.id, user_id: zak_fam.id,  is_home_team: nil)
Pick.create(game_id: saints_at_steelers.id, user_id: paul.id,     is_home_team: true)
Pick.create(game_id: saints_at_steelers.id, user_id: sarah.id,    is_home_team: true)
Pick.create(game_id: saints_at_steelers.id, user_id: charles.id,  is_home_team: true)
Pick.create(game_id: saints_at_steelers.id, user_id: barb.id,     is_home_team: false)
Pick.create(game_id: saints_at_steelers.id, user_id: vince.id,    is_home_team: true)
Pick.create(game_id: saints_at_steelers.id, user_id: anthony.id,  is_home_team: false)
Pick.create(game_id: saints_at_steelers.id, user_id: kim_jon.id,  is_home_team: true)
Pick.create(game_id: saints_at_steelers.id, user_id: mary_z.id,   is_home_team: true)
Pick.create(game_id: saints_at_steelers.id, user_id: alx_lh.id,   is_home_team: true)
Pick.create(game_id: saints_at_steelers.id, user_id: ben_t.id,    is_home_team: true)
Pick.create(game_id: saints_at_steelers.id, user_id: michael.id,  is_home_team: false)
Pick.create(game_id: saints_at_steelers.id, user_id: a_aj.id,     is_home_team: true)
Pick.create(game_id: saints_at_steelers.id, user_id: tommy.id,    is_home_team: true)
Pick.create(game_id: saints_at_steelers.id, user_id: jacob.id,    is_home_team: true)
Pick.create(game_id: saints_at_steelers.id, user_id: ann.id,      is_home_team: true)

Pick.create(game_id: panthers_at_vikings.id, user_id: bruce.id,    is_home_team: true)
Pick.create(game_id: panthers_at_vikings.id, user_id: matt.id,     is_home_team: true)
Pick.create(game_id: panthers_at_vikings.id, user_id: kristina.id, is_home_team: true)
Pick.create(game_id: panthers_at_vikings.id, user_id: danny.id,    is_home_team: true)
Pick.create(game_id: panthers_at_vikings.id, user_id: don.id,      is_home_team: true)
# Pick.create(game_id: panthers_at_vikings.id, user_id: zak_fam.id,  is_home_team: nil)
Pick.create(game_id: panthers_at_vikings.id, user_id: paul.id,     is_home_team: true)
Pick.create(game_id: panthers_at_vikings.id, user_id: sarah.id,    is_home_team: true)
Pick.create(game_id: panthers_at_vikings.id, user_id: charles.id,  is_home_team: true)
Pick.create(game_id: panthers_at_vikings.id, user_id: barb.id,     is_home_team: true)
Pick.create(game_id: panthers_at_vikings.id, user_id: vince.id,    is_home_team: false)
Pick.create(game_id: panthers_at_vikings.id, user_id: anthony.id,  is_home_team: false)
Pick.create(game_id: panthers_at_vikings.id, user_id: kim_jon.id,  is_home_team: true)
Pick.create(game_id: panthers_at_vikings.id, user_id: mary_z.id,   is_home_team: true)
Pick.create(game_id: panthers_at_vikings.id, user_id: alx_lh.id,   is_home_team: false)
Pick.create(game_id: panthers_at_vikings.id, user_id: ben_t.id,    is_home_team: false)
Pick.create(game_id: panthers_at_vikings.id, user_id: michael.id,  is_home_team: false)
Pick.create(game_id: panthers_at_vikings.id, user_id: a_aj.id,     is_home_team: false)
Pick.create(game_id: panthers_at_vikings.id, user_id: tommy.id,    is_home_team: false)
Pick.create(game_id: panthers_at_vikings.id, user_id: jacob.id,    is_home_team: true)
Pick.create(game_id: panthers_at_vikings.id, user_id: ann.id,      is_home_team: true)

Pick.create(game_id: cardinals_at_falcons.id, user_id: bruce.id,    is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: matt.id,     is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: kristina.id, is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: danny.id,    is_home_team: true)
Pick.create(game_id: cardinals_at_falcons.id, user_id: don.id,      is_home_team: false)
# Pick.create(game_id: cardinals_at_falcons.id, user_id: zak_fam.id,  is_home_team: nil)
Pick.create(game_id: cardinals_at_falcons.id, user_id: paul.id,     is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: sarah.id,    is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: charles.id,  is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: barb.id,     is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: vince.id,    is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: anthony.id,  is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: kim_jon.id,  is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: mary_z.id,   is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: alx_lh.id,   is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: ben_t.id,    is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: michael.id,  is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: a_aj.id,     is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: tommy.id,    is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: jacob.id,    is_home_team: false)
Pick.create(game_id: cardinals_at_falcons.id, user_id: ann.id,      is_home_team: false)

Pick.create(game_id: patriots_at_packers.id, user_id: bruce.id,    is_home_team: true)
Pick.create(game_id: patriots_at_packers.id, user_id: matt.id,     is_home_team: true)
Pick.create(game_id: patriots_at_packers.id, user_id: kristina.id, is_home_team: true)
Pick.create(game_id: patriots_at_packers.id, user_id: danny.id,    is_home_team: false)
Pick.create(game_id: patriots_at_packers.id, user_id: don.id,      is_home_team: true)
# Pick.create(game_id: patriots_at_packers.id, user_id: zak_fam.id,  is_home_team: nil)
Pick.create(game_id: patriots_at_packers.id, user_id: paul.id,     is_home_team: true)
Pick.create(game_id: patriots_at_packers.id, user_id: sarah.id,    is_home_team: false)
Pick.create(game_id: patriots_at_packers.id, user_id: charles.id,  is_home_team: true)
Pick.create(game_id: patriots_at_packers.id, user_id: barb.id,     is_home_team: true)
Pick.create(game_id: patriots_at_packers.id, user_id: vince.id,    is_home_team: true)
Pick.create(game_id: patriots_at_packers.id, user_id: anthony.id,  is_home_team: true)
Pick.create(game_id: patriots_at_packers.id, user_id: kim_jon.id,  is_home_team: true)
Pick.create(game_id: patriots_at_packers.id, user_id: mary_z.id,   is_home_team: false)
Pick.create(game_id: patriots_at_packers.id, user_id: alx_lh.id,   is_home_team: true)
Pick.create(game_id: patriots_at_packers.id, user_id: ben_t.id,    is_home_team: true)
Pick.create(game_id: patriots_at_packers.id, user_id: michael.id,  is_home_team: true)
Pick.create(game_id: patriots_at_packers.id, user_id: a_aj.id,     is_home_team: true)
Pick.create(game_id: patriots_at_packers.id, user_id: tommy.id,    is_home_team: true)
Pick.create(game_id: patriots_at_packers.id, user_id: jacob.id,    is_home_team: true)
Pick.create(game_id: patriots_at_packers.id, user_id: ann.id,      is_home_team: true)

Pick.create(game_id: broncos_at_chiefs.id, user_id: bruce.id,    is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: matt.id,     is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: kristina.id, is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: danny.id,    is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: don.id,      is_home_team: true)
# Pick.create(game_id: broncos_at_chiefs.id, user_id: zak_fam.id,  is_home_team: nil)
Pick.create(game_id: broncos_at_chiefs.id, user_id: paul.id,     is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: sarah.id,    is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: charles.id,  is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: barb.id,     is_home_team: true)
Pick.create(game_id: broncos_at_chiefs.id, user_id: vince.id,    is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: anthony.id,  is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: kim_jon.id,  is_home_team: true)
Pick.create(game_id: broncos_at_chiefs.id, user_id: mary_z.id,   is_home_team: true)
Pick.create(game_id: broncos_at_chiefs.id, user_id: alx_lh.id,   is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: ben_t.id,    is_home_team: true)
Pick.create(game_id: broncos_at_chiefs.id, user_id: michael.id,  is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: a_aj.id,     is_home_team: true)
Pick.create(game_id: broncos_at_chiefs.id, user_id: tommy.id,    is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: jacob.id,    is_home_team: true)
Pick.create(game_id: broncos_at_chiefs.id, user_id: ann.id,      is_home_team: true)

Pick.create(game_id: broncos_at_chiefs.id, user_id: bruce.id,    is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: matt.id,     is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: kristina.id, is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: danny.id,    is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: don.id,      is_home_team: false)
# Pick.create(game_id: broncos_at_chiefs.id, user_id: zak_fam.id,  is_home_team: nil)
Pick.create(game_id: broncos_at_chiefs.id, user_id: paul.id,     is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: sarah.id,    is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: charles.id,  is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: barb.id,     is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: vince.id,    is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: anthony.id,  is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: kim_jon.id,  is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: mary_z.id,   is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: alx_lh.id,   is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: ben_t.id,    is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: michael.id,  is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: a_aj.id,     is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: tommy.id,    is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: jacob.id,    is_home_team: false)
Pick.create(game_id: broncos_at_chiefs.id, user_id: ann.id,      is_home_team: false)

week14 = Week.create(year: 2014, week_number: 14)

cowboys_at_bears = Game.between('Cowboys', 'Bears',     Time.new(2014,12,04,19,30,0,"+06:00"))
week14.games << cowboys_at_bears
week14.games << Game.between('Ravens', 'Dolphins',   Time.new(2014,12,07,12,00,0,"+06:00"))
week14.games << Game.between('Colts', 'Browns',      Time.new(2014,12,07,12,00,0,"+06:00"))
week14.games << Game.between('Panthers', 'Saints',   Time.new(2014,12,07,12,00,0,"+06:00"))
week14.games << Game.between('Steelers', 'Bengals',  Time.new(2014,12,07,12,00,0,"+06:00"))
week14.games << Game.between('Buccaneers', 'Lions',  Time.new(2014,12,07,12,00,0,"+06:00"))
week14.games << Game.between('Texans', 'Jaguars',    Time.new(2014,12,07,12,00,0,"+06:00"))
week14.games << Game.between('Jets', 'Vikings',      Time.new(2014,12,07,12,00,0,"+06:00"))
week14.games << Game.between('Giants', 'Titans',     Time.new(2014,12,07,12,00,0,"+06:00"))
week14.games << Game.between('Rams', 'Redskins',     Time.new(2014,12,07,12,00,0,"+06:00"))
week14.games << Game.between('Bills', 'Broncos',     Time.new(2014,12,07,15,05,0,"+06:00"))
week14.games << Game.between('Chiefs', 'Cardinals',  Time.new(2014,12,07,15,05,0,"+06:00"))
week14.games << Game.between('49ers', 'Raiders',     Time.new(2014,12,07,15,25,0,"+06:00"))
week14.games << Game.between('Seahawks', 'Eagles',   Time.new(2014,12,07,15,25,0,"+06:00"))
week14.games << Game.between('Patriots', 'Chargers', Time.new(2014,12,07,19,30,0,"+06:00"))
week14.games << Game.between('Falcons', 'Packers',   Time.new(2014,12,07,19,30,0,"+06:00"))

Pick.create(game_id: cowboys_at_bears.id, user_id: bruce.id,    is_home_team: false)
Pick.create(game_id: cowboys_at_bears.id, user_id: matt.id,     is_home_team: false)
Pick.create(game_id: cowboys_at_bears.id, user_id: kristina.id, is_home_team: false)
Pick.create(game_id: cowboys_at_bears.id, user_id: danny.id,    is_home_team: true)
Pick.create(game_id: cowboys_at_bears.id, user_id: don.id,      is_home_team: false)
Pick.create(game_id: cowboys_at_bears.id, user_id: zak_fam.id,  is_home_team: true)
Pick.create(game_id: cowboys_at_bears.id, user_id: paul.id,     is_home_team: true)
Pick.create(game_id: cowboys_at_bears.id, user_id: sarah.id,    is_home_team: false)
Pick.create(game_id: cowboys_at_bears.id, user_id: barb.id,     is_home_team: true)
Pick.create(game_id: cowboys_at_bears.id, user_id: charles.id,  is_home_team: false)
Pick.create(game_id: cowboys_at_bears.id, user_id: anthony.id,  is_home_team: false)
Pick.create(game_id: cowboys_at_bears.id, user_id: vince.id,    is_home_team: false)
Pick.create(game_id: cowboys_at_bears.id, user_id: kim_jon.id,  is_home_team: false)
Pick.create(game_id: cowboys_at_bears.id, user_id: mary_z.id,   is_home_team: false)
Pick.create(game_id: cowboys_at_bears.id, user_id: alx_lh.id,   is_home_team: true)
Pick.create(game_id: cowboys_at_bears.id, user_id: michael.id,  is_home_team: true)
Pick.create(game_id: cowboys_at_bears.id, user_id: ben_t.id,    is_home_team: true)
# Pick.create(game_id: cowboys_at_bears.id, user_id: tommy.id,    is_home_team: nil)
Pick.create(game_id: cowboys_at_bears.id, user_id: a_aj.id,     is_home_team: false)
Pick.create(game_id: cowboys_at_bears.id, user_id: jacob.id,    is_home_team: true)
Pick.create(game_id: cowboys_at_bears.id, user_id: ann.id,      is_home_team: true)

bears_at_lions.finish(34, 17)
eagles_at_cowboys.finish(10, 33)
seahawks_at_49ers.finish(3, 19)
browns_at_bills.finish(26, 10)
chargers_at_ravens.finish(33, 34)
panthers_at_vikings.finish(31, 13)
bengals_at_bucs.finish(13, 14)
titans_at_texans.finish(45, 21)
redskins_at_colts.finish(49, 27)
giants_at_jaguars.finish(25, 24)
saints_at_steelers.finish(32, 35)
raiders_at_rams.finish(52, 0)
cardinals_at_falcons.finish(29, 18)
patriots_at_packers.finish(26, 21)
broncos_at_chiefs.finish(16, 29)
dolphins_at_jets.finish(13, 16)

Week.all.each do |week|
  Stat.create_all_for_week(week)
end
